pipeline {
    agent any

    environment {
        AWS_CRED        = 'aws_jr10_wanda'
        S3BucketName    = 'land-tasker-dev.net'
    }

    stages {
        stage('Build') {
            steps {
                sh 'npm install' // Install dependencies
                sh 'npm run build' // Run npm build command
            }
        }
        
        stage('Upload S3 Bucket') {
            steps {
                withAWS(credentials: AWS_CRED, region: 'ap-southeast-2') {
                    sh '''
                        aws s3 rm s3://$S3BucketName/ --recursive
                        aws s3 sync ./out/ s3://$S3BucketName/
                    '''
                }
            }
        }
    }
}
