pipeline {
    agent any

    environment {
        S3BucketName = 'jenkins.land-tasker-dev.net'
    }

    stages {
        stage('Check S3 Bucket') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY',
                    credentialsId: 'aws_jr10_wanda'
                ]]) {
                    script {
                        def filesToUpload = "out/*"

                        def bucketExists = sh(script: "aws s3 ls s3://$S3BucketName", returnStatus: true) == 0

                        if (bucketExists) {
                            stage('Upload Files') {
                                steps {
                                    withAWS(region: 'ap-southeast-2') {
                                        sh "aws s3 cp ${filesToUpload} s3://$S3BucketName/ --recursive"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
