pipeline {
    agent any

    parameters {
        booleanParam defaultValue: false, name: 'blBuild'
        booleanParam defaultValue: false, name: 'blUploadS3'
    }
    options {
        ansiColor('xterm')
    }

    environment {
        AWS_CRED        = 'aws_jr10_wanda'
        S3BucketName    = 'jenkins.land-tasker-dev.net'
    }

    stages {
        stage('Build') {
            when {expression{return params.blBuild}}
            steps {
                sh 'npm install' // Install dependencies
                sh 'npm run build' // Run npm build command
            }
        }
        
        stage('Upload S3 Bucket') {
            when {expression{return params.blUploadS3}}
            steps {
                withAWS(credentials: AWS_CRED, region: 'ap-southeast-2') {
                    dir('out') {
                        sh '''
                            aws s3 cp ${filesToUpload} s3://$S3BucketName/ --recursive
                        '''
                    }
                }
            }
        }
    }
}
