'use client';

import './globals.css';
import { Inter } from 'next/font/google';
// eslint-disable-next-line import/no-unresolved
import { ThemeProvider } from 'styled-components';
import StyledComponentsRegistry from './registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const light = {
  colors: {
    primary: 'rgb(44, 177, 188)',
    secondary: 'rgba(44, 177, 188, 0.8)',
    gray: 'rgb(72, 101, 129)',
  },
  borderRadius: '2px',
};

// dark theme
const dark = {
  colors: {
    primary: 'blue',
    secondary: 'rgba(44, 177, 188, 0.8)',
    gray: 'rgb(72, 101, 129)',
  },
  borderRadius: '2px',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ThemeProvider theme={light}>
            {children}
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
