import './globals.css';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from './registry';
import App from '../components/App/App';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Job post',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <App>
            {children}
          </App>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
